### ISSUE TITLE
Error in script (event clientMove)

### ISSUE THREAD

**Issue by SpieleArena** [Support-pp/Support-pp#28]
Nach einer frischen installation von s-pp kommt es zu folgenden fehler auf der version 2.0.4.9-2.3 

`2018-12-01T00:35:51+01:00 Error in script (event clientMove): TypeError: Cannot access member '0' of undefined at support-plusplus.js:2408:43 at forEach (<native code>) at support-plusplus.js:2405:21 at forEach (<native code>) at support-plusplus.js:2404:17 at forEach (<native code>) at getSupporter (support-plusplus.js:2403:13) at support-plusplus.js:2727:35 at forEach (<native code>) at support-plusplus.js:2715:9 `

https://hastebin.com/ojesagizid.makefile

Nach einem Downgrade (2.0.4.9-2.2) mit fast identischer einstellung geht es!

https://cdn.discordapp.com/attachments/303664307667730440/518210466263072783/sinusbot.spielearena.org-SinusBot3.jpeg

**Comment by esieben1310** [comment]
Ich bekomme bei ähnlicher Config ebenfalls eine Fehlermeldung:

```
2018-12-01T11:07:16+00:00 Error in script (event clientMove): TypeError: Cannot access member '0' of undefined at support-pp.js:2408:43 at forEach (<native code>) at support-pp.js:2405:21 at forEach (<native code>) at support-pp.js:2404:17 at forEach (<native code>) at getSupporter (support-pp.js:2403:13) at support-pp.js:2727:35 at forEach (<native code>) at support-pp.js:2715:9
2018-12-01T11:07:15+00:00 New connection status 4; Error 0
2018-12-01T11:07:15+00:00 New connection status 3; Error 0
2018-12-01T11:07:15+00:00 New connection status 2; Error 0
2018-12-01T11:07:15+00:00 New connection status 1; Error 0
2018-12-01T11:06:58+00:00 Starting instance ts3server://127.0.0.1?port=9987&nickname=SinusBot&password=&channel=&channelpassword=
2018-12-01T11:06:56+00:00 Could not create Notifications-Tabletable Notifications already exists
2018-12-01T11:06:56+00:00 Could not create WhisperReceive-Tabletable WhisperReceive already exists
2018-12-01T11:06:56+00:00 Could not create Chat-Tabletable Chat already exists
2018-12-01T11:06:54+00:00 Auto-Starting 9514de68-4dc8-48d6-8829-75b6eea30888/0bc71138-b228-40fd-a603-c35deca62e08 in 500 ms...
2018-12-01T11:06:54+00:00 Initialization complete
2018-12-01T11:06:54+00:00 Loading script support-pp
```
Config:
![support-pp_config_bug_test](https://user-images.githubusercontent.com/30735061/49327461-01bfaa00-f55a-11e8-8391-b3951a370cc0.PNG)

**Comment by esieben1310** [comment]
Dort bekomme ich den selben Fehler, jedoch funktionieren die anderen Funktionen.
Log:
```
2018-12-01T11:32:08+00:00 PRIVATE-CHAT [SinusBot] [B]Support | [/B]Du wirst ignoriert
2018-12-01T11:31:46+00:00 Error in script (event clientMove): TypeError: Cannot access member '0' of undefined at support-pp.js:2408:43 at forEach (<native code>) at support-pp.js:2405:21 at forEach (<native code>) at support-pp.js:2404:17 at forEach (<native code>) at getSupporter (support-pp.js:2403:13) at support-pp.js:2727:35 at forEach (<native code>) at support-pp.js:2715:9
2018-12-01T11:30:58+00:00 New connection status 4; Error 0
2018-12-01T11:30:58+00:00 New connection status 3; Error 0
2018-12-01T11:30:58+00:00 New connection status 2; Error 0
2018-12-01T11:30:56+00:00 New connection status 1; Error 0
2018-12-01T11:30:42+00:00 Starting instance ts3server://366.dat-ts.de?port=9987&nickname=SinusBot&password=&channel=&channelpassword=
2018-12-01T11:30:37+00:00 Could not create Notifications-Tabletable Notifications already exists
2018-12-01T11:30:37+00:00 Could not create WhisperReceive-Tabletable WhisperReceive already exists
2018-12-01T11:30:37+00:00 Could not create Chat-Tabletable Chat already exists
```

Config ist die selbe, nur die Gruppen ID´s sind angepasst.

**Comment by Lapotor** [comment]
@SpieleArena könntest du uns noch das Betriebssystem nennen auf dem Sinusbot läuft.

**Comment by VerHext** [comment]
@esieben1310 könntest du bitte ein Gist mit Log lvl 12 bereitstellen. Hast du dem Sinusbot auch wirklich die Admin Server Gruppe gesetzt?

**Comment by esieben1310** [comment]
Ja, der Bot hat Admin Rechte.
Log:
```
2018-12-01T11:50:12+00:00 TS/ERR 2564 e'access to default group is forbidden' x'' r'PR:{58fe413a-7420-4166-a22f-882d4386656c}:27/GCLL'
2018-12-01T11:50:11+00:00 PRIVATE-CHAT [SinusBot] [B]Support | [/B]Du wirst ignoriert
2018-12-01T11:50:11+00:00 Error in script (event clientMove): TypeError: Cannot access member '0' of undefined at support-pp.js:2408:43 at forEach (<native code>) at support-pp.js:2405:21 at forEach (<native code>) at support-pp.js:2404:17 at forEach (<native code>) at getSupporter (support-pp.js:2403:13) at support-pp.js:2727:35 at forEach (<native code>) at support-pp.js:2715:9
2018-12-01T11:50:11+00:00 New connection status 4; Error 0
2018-12-01T11:50:11+00:00 uuiui joined the channel
2018-12-01T11:50:11+00:00 New connection status 3; Error 0
2018-12-01T11:50:11+00:00 New connection status 2; Error 0
2018-12-01T11:50:10+00:00 New connection status 1; Error 0
2018-12-01T11:49:59+00:00 TS>DUMP defined! Dumpdir is: C:\SinusBot\data\ts3\9514de68-4dc8-48d6-8829-75b6eea30888\0bc71138-b228-40fd-a603-c35deca62e08\crashdumps
2018-12-01T11:49:59+00:00 TS>Crashdump ENABLED, directory is: C:\SinusBot\data\ts3\9514de68-4dc8-48d6-8829-75b6eea30888\0bc71138-b228-40fd-a603-c35deca62e08\crashdumps
2018-12-01T11:49:53+00:00 Starting instance ts3server://366.dat-ts.de?port=9987&nickname=SinusBot&password=&channel=&channelpassword=
2018-12-01T11:49:51+00:00 Could not create Notifications-Tabletable Notifications already exists
2018-12-01T11:49:51+00:00 Could not create WhisperReceive-Tabletable WhisperReceive already exists
2018-12-01T11:49:51+00:00 Could not create Chat-Tabletable Chat already exists
2018-12-01T11:49:51+00:00 About to run.
2018-12-01T11:49:51+00:00 Prespawn.
2018-12-01T11:49:51+00:00 Auto-Starting 9514de68-4dc8-48d6-8829-75b6eea30888/0bc71138-b228-40fd-a603-c35deca62e08 in 500 ms...
2018-12-01T11:49:51+00:00 Initialization complete
2018-12-01T11:49:51+00:00 Loading script support-pp
```

**Comment by SpieleArena** [comment]
> 
> 
> @SpieleArena könntest du uns noch das Betriebssystem nennen auf dem Sinusbot läuft.

Debian 9 Jessi

**Comment by SpieleArena** [comment]
> 
> 
> Ja, der Bot hat Admin Rechte.
> Log:
> 
> ```
> 2018-12-01T11:50:12+00:00 TS/ERR 2564 e'access to default group is forbidden' x'' r'PR:{58fe413a-7420-4166-a22f-882d4386656c}:27/GCLL'
> 2018-12-01T11:50:11+00:00 PRIVATE-CHAT [SinusBot] [B]Support | [/B]Du wirst ignoriert
> 2018-12-01T11:50:11+00:00 Error in script (event clientMove): TypeError: Cannot access member '0' of undefined at support-pp.js:2408:43 at forEach (<native code>) at support-pp.js:2405:21 at forEach (<native code>) at support-pp.js:2404:17 at forEach (<native code>) at getSupporter (support-pp.js:2403:13) at support-pp.js:2727:35 at forEach (<native code>) at support-pp.js:2715:9
> 2018-12-01T11:50:11+00:00 New connection status 4; Error 0
> 2018-12-01T11:50:11+00:00 uuiui joined the channel
> 2018-12-01T11:50:11+00:00 New connection status 3; Error 0
> 2018-12-01T11:50:11+00:00 New connection status 2; Error 0
> 2018-12-01T11:50:10+00:00 New connection status 1; Error 0
> 2018-12-01T11:49:59+00:00 TS>DUMP defined! Dumpdir is: C:\SinusBot\data\ts3\9514de68-4dc8-48d6-8829-75b6eea30888\0bc71138-b228-40fd-a603-c35deca62e08\crashdumps
> 2018-12-01T11:49:59+00:00 TS>Crashdump ENABLED, directory is: C:\SinusBot\data\ts3\9514de68-4dc8-48d6-8829-75b6eea30888\0bc71138-b228-40fd-a603-c35deca62e08\crashdumps
> 2018-12-01T11:49:53+00:00 Starting instance ts3server://366.dat-ts.de?port=9987&nickname=SinusBot&password=&channel=&channelpassword=
> 2018-12-01T11:49:51+00:00 Could not create Notifications-Tabletable Notifications already exists
> 2018-12-01T11:49:51+00:00 Could not create WhisperReceive-Tabletable WhisperReceive already exists
> 2018-12-01T11:49:51+00:00 Could not create Chat-Tabletable Chat already exists
> 2018-12-01T11:49:51+00:00 About to run.
> 2018-12-01T11:49:51+00:00 Prespawn.
> 2018-12-01T11:49:51+00:00 Auto-Starting 9514de68-4dc8-48d6-8829-75b6eea30888/0bc71138-b228-40fd-a603-c35deca62e08 in 500 ms...
> 2018-12-01T11:49:51+00:00 Initialization complete
> 2018-12-01T11:49:51+00:00 Loading script support-pp
> ```

Also der bot hatte Admin Server Query rechte

**Comment by VerHext** [comment]
Admin Server Query rechte
Werden nicht von TeamSpeak unterstützt. Somit gibt es dafür auch keinen Support unserer Seite. Da jeodch das Problem auch bei einem Mitarbeiter von uns aufgetreten ist, der einen unterstütze Konfiguration des Rechtesystemes verwendet. Werden wir den Fall weiter untersuchen... Jedoch ist es mir bis jetzt nicht gelungen diesen Fehler zu rekonstruieren.

**Comment by SpieleArena** [comment]
> 
> 
> Admin Server Query rechte
> Werden nicht von TeamSpeak unterstützt. Somit gibt es dafür auch keinen Support unserer Seite. Da jeodch das Problem auch bei einem Mitarbeiter von uns aufgetreten ist, der einen unterstütze Konfiguration des Rechtesystemes verwendet. Werden wir den Fall weiter untersuchen... Jedoch ist es mir bis jetzt nicht gelungen diesen Fehler zu rekonstruieren.

Normalerweise hatt der bot ja keine AdminServerQuery rechte er hat standard "musikbot" rechte (kommt auf's selbe wie admin hinaus) diese hat er jatzt auch nur noch da AdminServerQuery etwas hevy ist und eigentlich die anderen rechte reichen da aber gestern gefragt wurde ob er denn alle permissions hat habe ich ihm die höchsten rechte auf meinem server gegeben!

**Comment by VerHext** [comment]
Die AdminServerQuerry, solltest du aber keinem client geben. Das wird mehrfach von TeamSpeak erläutert. Dabei können Probleme in der TS DB auftreten. Und im Notfall zu Sicherheitsproblemen führen.

**Comment by SpieleArena** [comment]
War wie gesagt nur um zu testen und diese rechte hat er auch nicht mehr...

**Comment by VerHext** [comment]
So nach dem ich endlich das Problem rekonstruieren konnte hier eine ausgebesserte Version.
Bitte mal ersetzen und mir Rückmeldung geben.

https://hastebin.com/cuqusohare.php

**Comment by esieben1310** [comment]
Ich habe die Version getestet und habe keine Fehler erhalten.

**Comment by VerHext** [comment]
@SpieleArena kannst du vlt. die Version nochmal testen?
